### ISSUE TITLE
locale missing?

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/postgres#2]
```
2017-5-20 11:50:03selecting dynamic shared memory implementation ... posix
2017-5-20 11:50:03creating configuration files ... ok
2017-5-20 11:50:03creating template1 database in /var/lib/postgresql/data/base/1 ... ok
2017-5-20 11:50:03initializing pg_authid ... ok
2017-5-20 11:50:03initializing dependencies ... ok
2017-5-20 11:50:03creating system views ... ok
2017-5-20 11:50:03loading system objects' descriptions ... ok
2017-5-20 11:50:03sh: locale: not found
2017-5-20 11:50:03creating collations ... ok
2017-5-20 11:50:03No usable system locales were found.
2017-5-20 11:50:03Use the option "--debug" to see details.
2017-5-20 11:50:03creating conversions ... ok
```

2017-5-20 11:50:03sh: locale: not found

**Comment by EugenMayer** [comment]
seems like fixing this wont be easy at all https://github.com/gliderlabs/docker-alpine/issues/144 .. alpine has no way to general locales yet

**Comment by EugenMayer** [comment]
Seems like the official image did not care about this any further https://github.com/docker-library/postgres/blob/54053ad27ac099abff3d4964bf7460fb9c541d5d/9.6/alpine/Dockerfile#L20 either, so it might be a nop here also

From my POV, you did all you need for this and we have to ignore it or create a locale stub which does nothing to avoid this error to show up in the logs

**Comment by blacklabelops** [comment]
Agreed
